### ISSUE TITLE
Could not find the label and dataset value in click event

### ISSUE THREAD

**Issue by contact2vikas** [sgratzl/chartjs-chart-wordcloud#15]
options: {

        onClick: (e) => {
          
      const canvasPosition = ctx.helpers.getRelativePosition(e, ctx);

}

Getting below error 

core.mjs:6461 ERROR TypeError: Cannot read properties of undefined (reading 'getRelativePosition')
    at Chart.onClick (app.component.ts:37:42)
    at callback (helpers.segment.js:92:1)
    at Chart._handleEvent (chart.esm.js:6090:17)
    at Chart._eventHandler (chart.esm.js:6072:1)
    at listener (chart.esm.js:5952:1)
    at Chart.event (chart.esm.js:3214:1)
    at helpers.segment.js:28:1
    at timer (zone.js:2561:1)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25444:1)

**Comment by sgratzl** [comment]
please ask the chart.js guys directly, since this is a just a plugin of chart.js and this related to chart.js itself

**Comment by contact2vikas** [comment]
Below is the reply from chat.js

I can't tell if this is an issue with chart.js itself or with chartjs-chart-wordcloud. Have you already reported this issue to the extension?

**Comment by sgratzl** [comment]
can you provide a complete example, e.g. on codepen or codesandbox. Without a complete example it is difficult to reproduce it
