### ISSUE TITLE
use with vue-chart-3

### ISSUE THREAD

**Issue by silvercent011** [sgratzl/chartjs-chart-wordcloud#18]
I'm having the following question...
How to use chartjs-chart-wordcloud with vue-chart-3 without errors?

```
main.ts - Vue render file

import { WordCloudController, WordElement } from 'chartjs-chart-wordcloud'
Chart.register(WordCloudController, WordElement)

```

```
Vue component file
<template>
            ...
            <div class="md:flex-1 w-full min-h-full">
                <WordCloudChart :chartData="chartData" />
            </div>
            ...
</template>

<script lang="ts">
import { computed, defineComponent, ref, watch, onMounted } from 'vue'
import { ChartData } from 'chart.js'
import { WordCloudChart } from "chartjs-chart-wordcloud";
...

export default defineComponent({
    components: { WordCloudChart},
...
    setup(props) {
         ...

        const wordsValues = computed(() => {
            return words.value.map((d) => d.value)
        })
        
        const wordsTitles = computed(() => {
            return words.value.map((d) => d.key)
        })

        onMounted(() => {
            getdpWordCloudData()
        })


        ...
        const chartData = computed<ChartData<"wordCloud">>(() => (<ChartData<"wordCloud">><unknown>{
            labels: words.value.map((e) => e.key),
            datasets: [
                {
                    label: "",
                    data: wordsValues.value,
                }
            ]
        }));

        return {chartData}
    },
})
</script>
```

## I get this error on browser console:

```runtime-core.esm-bundler.js:475         
       Uncaught (in promise) TypeError: Class constructor WordCloudChart cannot be invoked without 'new'
    at renderComponentRoot (runtime-core.esm-bundler.js:475:19)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4332:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160:29)
    at setupRenderEffect (runtime-core.esm-bundler.js:4458:9)
    at mountComponent (runtime-core.esm-bundler.js:4241:9)
    at processComponent (runtime-core.esm-bundler.js:4199:17)
    at patch (runtime-core.esm-bundler.js:3791:21)
    at mountChildren (runtime-core.esm-bundler.js:3987:13)
    at mountElement (runtime-core.esm-bundler.js:3896:17)
    at processElement (runtime-core.esm-bundler.js:3868:13)
```

**Comment by sgratzl** [comment]
this is a plugin for chart.js, chart.js is not a Vue.js library. You need some wrapper such as https://vue-chartjs.org/ in order to use chart.js in Vue.js

**Comment by silvercent011** [comment]
Yeah, i'm using [vue-chart-3](https://vue-chart-3.netlify.app/) as a wrapper, changing the implementation of code, the browser returns between two errors.

`TypeError: Class constructor WordCloudChart cannot be invoked without 'new'`

or 

`Uncaught TypeError: Cannot read properties of undefined (reading 'y')`

**Comment by sgratzl** [comment]
can you create an example e.g. on codesandbox with the code as far as you can get

**Comment by silvercent011** [comment]
Hello again :)

I've made some changes on implementation code and the wordcloud started working combined with vue-chart-3 wrapper. Sorry for wasted time. 

For another people that find the same problem, just follow the CodeSandbox url below:
https://codesandbox.io/s/floral-frost-78jytp?file=/src/App.vue
