### ISSUE TITLE
We are getting an error "ERROR Error: Canvas is already in use. Chart with ID '2' must be destroyed before the canvas can be reused."  while **rebinding** the chart from API,  

### ISSUE THREAD

**Issue by VikasSaxenaxcdify** [sgratzl/chartjs-chart-wordcloud#21]
We are getting an error "ERROR Error: Canvas is already in use. Chart with ID '2' must be destroyed before the canvas can be reused."  while **rebinding** the chart from API,  

we have used    
ctx.clear();   and   ctx.destroy()
method for clearing the canvas but getting errors while used
ERROR TypeError: ctx.destroy is not a functin

ERROR Error: Canvas is already in use. Chart with ID '2' must be destroyed before the canvas can be reused.
    at new Chart (chart.esm.js:5354:1)
    at new WordCloudChart (index.umd.js:747:1)
    at EmployeeComponent.wordcloudChart (employee.component.ts:281:21)
    at employee.component.ts:339:14
    at Object.next (Subscriber.js:110:1)
    at SafeSubscriber._next (Subscriber.js:60:1)
    at SafeSubscriber.next (Subscriber.js:31:1)
    at map.js:7:1
    at OperatorSubscriber._next (OperatorSubscriber.js:9:1)
    at OperatorSubscriber.next (Subscriber.js:31:1)

**Comment by sgratzl** [comment]
how is the given angular created error related to this plugin of chart.js? I would ask the devs who developed the angular chart.js binding
